<?php if(!isset($_SESSION)){session_start();}
    if(isset($_SESSION['id-nota-tinggal'])){
        unset($_SESSION['id-nota-tinggal']);
    }
    if(isset($_SESSION['id-nota-dp'])){
        unset($_SESSION['id-nota-dp']);
    }
    if(isset($_SESSION['username'])){
        unset($_SESSION['username']);
    }
    if(isset($_SESSION['email'])){
        unset($_SESSION['email']);
    }
    if(isset($_SESSION['tlpn'])){
        unset($_SESSION['tlpn']);
    }
    if(isset($_SESSION['alamat'])){
        unset($_SESSION['alamat']);
    }
    if(isset($_SESSION['type'])){
        unset($_SESSION['type']);
    }
    if(isset($_SESSION['seri-hp'])){
        unset($_SESSION['seri-hp']);
    }
    if(isset($_SESSION['imei'])){
        unset($_SESSION['imei']);
    }
    if(isset($_SESSION['merek'])){
        unset($_SESSION['merek']);
    }
    if(isset($_SESSION['seri-laptop'])){
        unset($_SESSION['seri-laptop']);
    }
    if(isset($_SESSION['kerusakan'])){
        unset($_SESSION['kerusakan']);
    }
    if(isset($_SESSION['kondisi'])){
        unset($_SESSION['kondisi']);
    }
    if(isset($_SESSION['kelengkapan'])){
        unset($_SESSION['kelengkapan']);
    }
    if(isset($_SESSION['dp'])){
        unset($_SESSION['dp']);
    }
    if(isset($_SESSION['biaya'])){
        unset($_SESSION['biaya']);
    }